# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('size_flag', models.CharField(choices=[('Regular', 'Regular'), ('Sample', 'Sample'), ('Tester', 'Tester'), ('Others', 'Others')], default='Regular', max_length=7)),
                ('price_cost', models.FloatField(default=0)),
                ('price_bought', models.FloatField(default=0)),
                ('price_wholesale', models.FloatField(default=0)),
                ('price_retail', models.FloatField(default=0)),
                ('free_shipping', models.CharField(choices=[('Always', 'Always'), ('Normal', 'Normal'), ('Special', 'Special')], max_length=7, null=True)),
                ('order_min', models.IntegerField(default=1)),
                ('order_max', models.IntegerField(default=1)),
                ('desc_header', models.CharField(blank=True, max_length=100)),
                ('desc_body', models.TextField(blank=True)),
                ('status', models.BooleanField(choices=[(True, 'active'), (False, 'inactive')], default=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publish', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='brands.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='category.Category')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='suppliers.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Color', 'Color'), ('Size', 'Size'), ('Weight', 'Weight')], default='Color', max_length=7)),
                ('value', models.CharField(max_length=80)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attr', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('reference_type', models.IntegerField(default=0)),
                ('reference_id', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock_history', to='products.Product')),
            ],
        ),
    ]
