# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
